// src/pages/FileExplorer/Breadcrumb.tsx
import { Link } from "react-router-dom";

interface BreadcrumbProps {
  path: string[];
}

export function Breadcrumb({ path }: BreadcrumbProps) {
  return (
    <div className="flex flex-row">
      {path.map((p, i) => (
        <span key={i}>
          <Link
            to={`/file/${path.slice(0, i + 1).join("/")}`}
            className="text-lg hover:underline"
          >
            {p}
          </Link>
          {i !== path.length - 1 && (
            <span className="mx-1"> &gt; </span>
          )}
        </span>
      ))}
    </div>
  );
}

// src/pages/FileExplorer/Breadcrumb.vue
<script setup lang="ts">

defineProps({
  path: Array<String>
});
</script>

<template>
  <div id="breadcrumb">
    <template v-for="(p, i) in path">
      <RouterLink :to="`/file/${path?.slice(0, i + 1).join('/')}`">{{p}}</RouterLink>
      <span v-if="i != path!.length - 1"> > </span>
    </template>
  </div>
</template>

<style scoped>
#breadcrumb {
  display: flex;
  flex-direction: row;
}

#breadcrumb span {
  margin-left: 4px;
  margin-right: 4px;
}

#breadcrumb a {
  font-size: 1.15rem;
}

#breadcrumb a:hover {
  text-decoration: underline;
}
</style>
