// src/pages/FileExplorer/ExplorerPage.vue
<script setup lang="ts">
import Breadcrumb from "./Breadcrumb.vue";
import FolderAndFiles from "./FolderAndFiles.vue";
import {Dialog, Divider, InputText, Popover, useToast} from "primevue";

import {FileSystem, FileType} from "../../ts/utils/FileSystem.ts";
import {ref, watch} from "vue";
import {BaseDirectory, mkdir} from "@tauri-apps/plugin-fs";
import {useRouter} from "vue-router";

const props = defineProps<{ path: string[], }>();
const entries = ref(await FileSystem.load(props.path));
const createFolderName = ref("Unnamed Folder");
let dialogOpen = ref(false);
let popover = ref();

const router = useRouter();
const toast = useToast();

watch(() => props.path, async (newProp, _prevProp) => {
  await reloadFs(newProp);
});

function openCreateNewFile(event: MouseEvent) {
  popover.value.toggle(event);
}

async function reloadFs(path?: string[]) {
  entries.value = await FileSystem.load(path ?? props.path);
}

async function createFolder() {
  await mkdir(`${props.path.join("/")}/${createFolderName.value}`, {baseDir: BaseDirectory.AppData});
  await reloadFs();
  toast.add({ 
    severity: "success",
    summary: "New folder created",
    life: 4000
  })
}

async function newFile(title: string, type: FileType) {
  const path = props.path.join("/");
  const name = await FileSystem.getUniqueFileName(title, type, path);
  
  await FileSystem.createFile(path, name, new ArrayBuffer(0));
  await router.replace(`/${type}/${path}/${name}`)
}
</script>

<template>
  <main>
    <div id="top-bar">
      <div id="left">
        <div id="breadcrumb" class="bubble">
          <Breadcrumb :path="path"></Breadcrumb>
        </div>
      </div>
      <div id="right">
        <Popover ref="popover">
          <div id="popovers">
            <button class="btn" @click="dialogOpen = true;popover.hide();">
              <span class="icon pi pi-folder-plus"/>
              <span>New Folder</span>
            </button>

            <Divider/>

            <!--            <button class="btn">-->
            <!--              <span class="icon pi pi-file-import"/>-->
            <!--              <span>Import Myelin File</span>-->
            <!--            </button>-->
            <!---->
            <!--            <button class="btn">-->
            <!--              <span class="icon pi pi-file-pdf"/>-->
            <!--              <span>Import PDF</span>-->
            <!--            </button>-->

            <!--            <Divider/>-->

            <button class="btn" @click="newFile('Untitled Document', 'mdoc')">
              <span class="icon pi pi-file-plus"/>
              <span>New Document</span>
            </button>

            <button class="btn" @click="newFile('Untitled Canvas', 'mcanvas')">
              <svg class="icon" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="18px"
                   fill="currentColor">
                <path
                    d="M280-280h84l240-238-86-86-238 238v86Zm352-266 42-44q6-6 6-14t-6-14l-56-56q-6-6-14-6t-14 6l-44 42 86 86ZM200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h168q13-36 43.5-58t68.5-22q38 0 68.5 22t43.5 58h168q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm0-80h560v-560H200v560Zm280-590q13 0 21.5-8.5T510-820q0-13-8.5-21.5T480-850q-13 0-21.5 8.5T450-820q0 13 8.5 21.5T480-790ZM200-200v-560 560Z"/>
              </svg>
              <span>New Canvas</span>
            </button>
          </div>
        </Popover>
        <button id="create" class="foreground-item" @click="openCreateNewFile($event)">
          <span class="icon pi pi-plus"/>
        </button>
      </div>
    </div>
    <FolderAndFiles
        :directories="entries[0]"
        :files="entries[1]"
        :path="props.path"
        @reload="reloadFs()"/>
  </main>

  <Dialog modal v-model:visible="dialogOpen">
    <template #container="{ closeCallback }">
      <div class="dialog bubble">
        <h1>Create Folder</h1>
        <InputText autofocus placeholder="Folder Name" v-model="createFolderName"/>
        <div class="dialog-buttons">
          <button class="btn" @click="closeCallback()">
            <span>Cancel</span>
          </button>
          <button class="btn" @click="closeCallback();createFolder();">
            <span>Confirm</span>
          </button>
        </div>
      </div>
    </template>
  </Dialog>
</template>

<style scoped>
main {
  padding: 32px;
  gap: var(--p-gap-same-context);
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  width: 100%;
  height: 100%;
  box-sizing: border-box;

  /* Add this to prevent expanding */
  min-height: 0;
  overflow: hidden;
}

#top-bar {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  align-self: stretch;
}

#top-bar #right #create {
  transition: var(--p-transition);
}

#top-bar #right #create:hover {
  background-color: var(--c-primary);
}

#popovers {
  display: flex;
  flex-direction: column;
}
</style>

// src/pages/FileExplorer/ExplorerPage.tsx
import { useEffect, useState, useCallback } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Breadcrumb } from "./Breadcrumb";
import { FolderAndFiles } from "./FolderAndFiles";
import { FileSystem, FileType, MyelinFile } from "@/ts/utils/FileSystem";
import { BaseDirectory, create, mkdir } from "@tauri-apps/plugin-fs";
import { join } from "@tauri-apps/api/path";
import { toast } from "sonner";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import PlusIcon from "@/assets/icons/plus.svg?react";
import FolderPlusIcon from "@/assets/icons/folder-plus.svg?react";
import FilePlusIcon from "@/assets/icons/file-plus.svg?react";
import CanvasIcon from "@/assets/icons/canvas-icon.svg?react";

export function ExplorerPage() {
  const params = useParams();
  const path = params["*"]?.split("/").filter(Boolean) ?? ["Home"];
  const navigate = useNavigate();

  const [directories, setDirectories] = useState<string[]>([]);
  const [files, setFiles] = useState<MyelinFile[]>([]);
  const [loading, setLoading] = useState(true);
  const [folderDialogOpen, setFolderDialogOpen] = useState(false);
  const [createFolderName, setCreateFolderName] = useState("Unnamed Folder");

  const reloadFs = useCallback(async (p?: string[]) => {
    setLoading(true);
    try {
      const [dirs, fs] = await FileSystem.loadDirectory(p ?? path);
      setDirectories(dirs);
      setFiles(fs);
    } catch (err) {
      console.error("Failed to load directory:", err);
    }
    setLoading(false);
  }, [path.join("/")]);

  useEffect(() => {
    reloadFs();
  }, [reloadFs]);

  async function createFolder() {
    await mkdir(`${await join(...path)}/${createFolderName}`, { baseDir: BaseDirectory.AppData });
    await reloadFs();
    toast.success("New folder created");
    setFolderDialogOpen(false);
  }

  async function newFile(title: string, type: FileType) {
    const p = await join(...path);
    const name = await FileSystem.getUniqueFileName(title, type, p);
    const file = await create(await join(p, name), { baseDir: BaseDirectory.AppData });
    await file.close();
    navigate(`/${type}/${path.join("/")}/${name}`);
  }

  if (loading) {
    return (
      <div className="flex justify-center items-center w-full h-full">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    );
  }

  return (
    <>
      <main className="p-8 gap-4 flex flex-col items-start w-full h-full box-border min-h-0 overflow-hidden">
        <div className="flex flex-row justify-between items-center self-stretch">
          <div className="bg-white rounded-lg shadow-sm p-4">
            <Breadcrumb path={path} />
          </div>
          <div>
            <DropdownMenu>
              <DropdownMenuTrigger className="bg-secondary shadow-sm rounded-lg p-4 transition-colors hover:bg-primary cursor-pointer border-none outline-none">
                <PlusIcon width={20} height={20} className="text-icons" />
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onClick={() => { setCreateFolderName("Unnamed Folder"); setFolderDialogOpen(true); }}>
                  <FolderPlusIcon width={16} height={16} className="mr-2" />
                  New Folder
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem onClick={() => newFile("Untitled Document", "mdoc")}>
                  <FilePlusIcon width={16} height={16} className="mr-2" />
                  New Document
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => newFile("Untitled Canvas", "mcanvas")}>
                  <CanvasIcon width={16} height={16} className="mr-2" />
                  New Canvas
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>

        <FolderAndFiles
          directories={directories}
          files={files}
          path={path}
          onReload={() => reloadFs()}
        />
      </main>

      <Dialog open={folderDialogOpen} onOpenChange={setFolderDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create Folder</DialogTitle>
          </DialogHeader>
          <Input
            autoFocus
            placeholder="Folder Name"
            value={createFolderName}
            onChange={(e) => setCreateFolderName(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter") createFolder(); }}
          />
          <DialogFooter>
            <Button variant="ghost" onClick={() => setFolderDialogOpen(false)}>Cancel</Button>
            <Button onClick={createFolder}>Confirm</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
