// src/pages/FileExplorer/FolderItem.tsx
import { Link } from "react-router-dom";
import FolderIcon from "@/assets/icons/folder.svg?react";

interface FolderItemProps {
  title: string;
  link: string;
  path: string[];
  openCtx: (event: React.MouseEvent, item: string[]) => void;
}

export function FolderItem({ title, link, path, openCtx }: FolderItemProps) {
  return (
    <Link
      to={`/file/${link}`}
      className="flex flex-row justify-start items-center gap-4 bg-secondary rounded-lg p-4 shadow-sm transition-colors hover:bg-primary cursor-pointer"
      onContextMenu={(e) => {
        e.preventDefault();
        openCtx(e, path);
      }}
    >
      <FolderIcon className="w-6 text-accent" />
      <span>{title}</span>
    </Link>
  );
}

// src/pages/FileExplorer/FolderItem.vue
<script setup lang="ts">
const {title = 'Folder Name', link} = defineProps<{
  title?: string,
  link?: string,
  openCtx: (event: PointerEvent, item: string) => void,
}>()
</script>

<template>
  <RouterLink 
      :to="`/file/${link}`" 
      id="item"
      class="foreground-item"
      @contextmenu="openCtx($event, link!)"
      aria-haspopup="true">
    <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
      <path fill="currentColor"
            d="M64 480H448c35.3 0 64-28.7 64-64V160c0-35.3-28.7-64-64-64H288c-10.1 0-19.6-4.7-25.6-12.8L243.2 57.6C231.1 41.5 212.1 32 192 32H64C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64z"
      />
    </svg>
    <span>{{ title }}</span>
  </RouterLink>
</template>

<style scoped>
svg path {
  color: var(--c-accent);
}

svg {
  width: 24px;
}

#item {
  display: flex;
  flex-direction: row;
  justify-content: start;
  align-items: center;
  gap: var(--p-gap-same-context);
  transition: var(--p-transition);
}

#item:hover {
  background-color: var(--c-primary);
  cursor: pointer;
}
</style>
