// src/pages/FileExplorer/FolderAndFiles.tsx
import { useRef, useState } from "react";
import { FolderItem } from "./FolderItem";
import { FileItem } from "./FileItem";
import { FileSystem, MyelinFile } from "@/ts/utils/FileSystem";
import { toast } from "sonner";
import { basename, extname, join } from "@tauri-apps/api/path";
import { BaseDirectory, stat } from "@tauri-apps/plugin-fs";
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuTrigger,
} from "@/components/ui/context-menu";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

interface FolderAndFilesProps {
  path: string[];
  directories: string[];
  files: MyelinFile[];
  onReload: () => void;
}

export function FolderAndFiles({ path, directories, files, onReload }: FolderAndFilesProps) {
  const [selectedItem, setSelectedItem] = useState<string[] | null>(null);
  const [renameDialogOpen, setRenameDialogOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [renameName, setRenameName] = useState("");
  const triggerRef = useRef<HTMLDivElement>(null);

  async function handleRenameClick() {
    if (!selectedItem) return;
    const p = await join(...selectedItem);
    const isFile = (await stat(p, { baseDir: BaseDirectory.AppData })).isFile;

    if (isFile) {
      let name = await basename(p, await extname(p));
      name = name.slice(0, name.length - 1);
      setRenameName(name);
    } else {
      setRenameName(await basename(p));
    }

    setRenameDialogOpen(true);
  }

  async function handleRename() {
    if (!selectedItem || !renameName) return;
    await FileSystem.renameFileOrFolder(await join(...selectedItem), renameName);
    onReload();
    toast.success("Renamed successfully", { description: `Renamed to ${renameName}` });
    setRenameDialogOpen(false);
  }

  async function handleDelete() {
    if (!selectedItem) return;
    await FileSystem.deleteFileOrFolder(selectedItem);
    onReload();
    setDeleteDialogOpen(false);
  }

  function openCtx(event: React.MouseEvent, item: string[]) {
    setSelectedItem(item);
    // Programmatically trigger context menu at the right position
    const contextEvent = new MouseEvent('contextmenu', {
      bubbles: true,
      clientX: event.clientX,
      clientY: event.clientY,
    });
    triggerRef.current?.dispatchEvent(contextEvent);
  }

  return (
    <>
      <ContextMenu>
        <ContextMenuTrigger ref={triggerRef} className="grow self-stretch p-8 flex flex-col items-start justify-start gap-8 overflow-y-auto min-h-0 h-full bg-white rounded-lg shadow-sm">
            <div className="flex flex-col items-start justify-start self-stretch gap-4">
              <h1 className="text-lg font-normal m-0">Folders</h1>
              {directories.length > 0 ? (
                <div className="self-stretch grid grid-cols-[repeat(auto-fill,minmax(300px,18%))] gap-y-5 gap-x-10">
                  {directories.map((dir) => (
                    <FolderItem
                      key={dir}
                      title={dir}
                      link={path.join("/") + `/${dir}`}
                      path={path.concat(dir)}
                      openCtx={openCtx}
                    />
                  ))}
                </div>
              ) : (
                <h2 className="text-base font-normal m-0">Create a new folder</h2>
              )}
            </div>

            <div className="flex flex-col items-start justify-start self-stretch gap-4">
              <h1 className="text-lg font-normal m-0">Files</h1>
              {files.length > 0 ? (
                <div className="self-stretch grid grid-cols-[repeat(auto-fill,minmax(300px,18%))] gap-y-5 gap-x-10">
                  {files.map((file) => (
                    <FileItem
                      key={file.name}
                      file={file}
                      link={path.join("/") + `/${file.name}.${file.type}`}
                      path={path.concat(`${file.name}.${file.type}`)}
                      openCtx={openCtx}
                    />
                  ))}
                </div>
              ) : (
                <h2 className="text-base font-normal m-0">Create a new file</h2>
              )}
            </div>
        </ContextMenuTrigger>

        <ContextMenuContent>
          <ContextMenuItem onClick={handleRenameClick}>
            Rename
          </ContextMenuItem>
          <ContextMenuItem
            className="text-destructive"
            onClick={() => setDeleteDialogOpen(true)}
          >
            Delete
          </ContextMenuItem>
        </ContextMenuContent>
      </ContextMenu>

      <Dialog open={renameDialogOpen} onOpenChange={setRenameDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Rename</DialogTitle>
          </DialogHeader>
          <Input
            autoFocus
            placeholder="Name"
            value={renameName}
            onChange={(e) => setRenameName(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter") handleRename(); }}
          />
          <DialogFooter>
            <Button variant="ghost" onClick={() => setRenameDialogOpen(false)}>Cancel</Button>
            <Button onClick={handleRename}>Confirm</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Do you want to delete this?</AlertDialogTitle>
            <AlertDialogDescription>This can not be undone!</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={handleDelete} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}

// src/pages/FileExplorer/FolderAndFiles.vue
<script setup lang="ts">
import FolderItem from "./FolderItem.vue";
import FileItem from "./FileItem.vue";
import {FileSystem, MyelinFile} from "../../ts/utils/FileSystem.ts";
import {ref} from "vue";
import {ConfirmDialog, ContextMenu, Dialog, InputText, useConfirm, useToast} from "primevue";
import {MenuItem} from "primevue/menuitem";
import {basename, extname} from "@tauri-apps/api/path";
import {BaseDirectory, stat} from '@tauri-apps/plugin-fs';

const emit = defineEmits(["reload"]);
defineProps<{
  path: string[],
  directories: string[],
  files: MyelinFile[]
}>();

const menu = ref();
const selectedItem = ref<null | string>(null);
const renameDialogOpen = ref(false);
const renameName = ref<null | string>(null);

const confirm = useConfirm();
const toast = useToast();

const items: MenuItem[] = [
  {
    label: 'Rename',
    icon: 'pi pi-pen-to-square',
    command: async () => {
      const path = selectedItem.value!;
      const isFile = (await stat(path, { baseDir: BaseDirectory.AppData })).isFile;
      
      if (isFile) {
        let name = await basename(path, await extname(path));
        name = name.slice(0, name.length - 1);
        renameName.value = name;
      } else {
        renameName.value = await basename(path);
      }
      
      renameDialogOpen.value = true;
    }
  },
  {
    label: 'Delete',
    icon: 'pi pi-trash',
    command: () => {
      confirm.require({
        header: 'Do you want to delete this?',
        message: 'This can not be undone!',
        rejectLabel: 'Cancel',
        rejectProps: {
          label: 'Cancel',
          severity: 'secondary',
        },
        acceptProps: {
          label: 'Delete',
          severity: 'danger'
        },
        accept: async () => {
          await FileSystem.deleteFileOrFolder(selectedItem.value!);
          emit('reload');
        },
      });
    }
  },
];

function openCtx(event: PointerEvent, item: string) {
  selectedItem.value = item;
  console.log(selectedItem.value);
  menu.value.show(event);
}

async function rename() {
  await FileSystem.renameFileOrFolder(selectedItem.value!, renameName.value!);
  emit('reload');
  toast.add({
    severity: "success",
    summary: "Renamed successfully",
    detail: `Renamed to ${renameName.value}`,
    life: 4000,
  });
}
</script>

<template>
  <div id="view" class="bubble">
    <div class="section">
      <h1>Folders</h1>
      <div v-if="directories.length > 0" class="items">
        <template v-for="dir in directories">
          <FolderItem
              :title="dir"
              :link="path.join('/') + `/${dir}`"
              :open-ctx/>
        </template>
      </div>
      <div v-else>
        <h2>Create a new folder</h2>
      </div>
    </div>
    <div class="section">
      <h1>Files</h1>
      <div v-if="files.length > 0" class="items">
        <template v-for="file in files">
          <FileItem
              :file="file"
              :link="path.join('/') + `/${file.name}.${file.type}`"
              :open-ctx/>
        </template>
      </div>
      <div v-else>
        <h2>Create a new file</h2>
      </div>
    </div>
    <ContextMenu ref="menu" :model="items"/>
    <ConfirmDialog/>
    
    <Dialog modal v-model:visible="renameDialogOpen">
      <template #container="{ closeCallback }">
        <div class="dialog bubble">
          <h1>Rename Folder</h1>
          <InputText autofocus placeholder="Folder Name" v-model="renameName"/>
          <div class="dialog-buttons">
            <button class="btn" @click="closeCallback()">
              <span>Cancel</span>
            </button>
            <button class="btn" @click="closeCallback();rename();">
              <span>Confirm</span>
            </button>
          </div>
        </div>
      </template>
    </Dialog>
  </div>
</template>

<style scoped>
#view {
  flex-grow: 1;
  align-self: stretch;
  padding: 32px;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: flex-start;
  gap: var(--p-gap-diff-context);
  overflow-y: auto;

  /* Add these to ensure proper sizing */
  min-height: 0;
  height: 100%;
}

.section {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: flex-start;
  align-self: stretch;
  gap: var(--p-gap-same-context);
}

.items {
  align-self: stretch;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 18%));
  row-gap: 20px;
  column-gap: 40px;
}
</style>
